# Generated by Django 4.2.3 on 2023-07-09 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=256, unique=True, verbose_name='用户名称')),
                ('nickname', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户呢称')),
                ('password', models.CharField(max_length=256, verbose_name='用户密码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='用户头像')),
                ('status', models.SmallIntegerField(choices=[('1', '正常'), ('0', '删除')], default=1, verbose_name='用户状态')),
                ('is_super', models.BooleanField(default=False, verbose_name='是否为超级管理员')),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=256, unique=True, verbose_name='用户名称')),
                ('realname', models.CharField(blank=True, max_length=256, null=True, verbose_name='真实姓名')),
                ('sex', models.SmallIntegerField(choices=[('2', '未知'), ('1', '男'), ('0', '女')], default=2, verbose_name='用户性别')),
                ('address', models.CharField(max_length=128, verbose_name='住址')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.user', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'account_user_profile',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, verbose_name='用户名称')),
                ('login_type', models.CharField(max_length=128, verbose_name='账号平台')),
                ('ip', models.CharField(default='', max_length=64, verbose_name='IP地址')),
                ('ua', models.CharField(default='', max_length=256, verbose_name='UA信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='account.user')),
            ],
            options={
                'db_table': 'account_login_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
