# Generated by Django 4.2.3 on 2023-07-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_question_classify_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collect_questions',
            field=models.ManyToManyField(to='accounts.question'),
        ),
    ]
