# Generated by Django 4.2.3 on 2023-07-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(verbose_name='订单ID')),
                ('comment', models.TextField(verbose_name='评论内容')),
                ('score', models.FloatField(default=5, verbose_name='评分')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='order_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='sight_comment',
        ),
        migrations.DeleteModel(
            name='OrderComment',
        ),
        migrations.DeleteModel(
            name='SightComment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
